name: documentation
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '>= 18.0'
      - name: Build
        run: |
          export BASE_URL=pr-$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          yarn install --frozen-lockfile
          yarn build
      - name: Upload Build Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: build
  deploy:
    name: Deploy to GitHub Pages
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Publish
        uses: actions/deploy-pages@v4
