name: documentation

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
    branches:
      - main

concurrency: preview-${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '>= 18.0'
      - name: Build Preview (PR)
        if: github.event_name == 'pull_request'
        run: |
          export BASE_URL=/pr-preview/pr-$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          yarn install --frozen-lockfile
          yarn build
      - name: Build Preview (main)
        if: github.event_name == 'push'
        run: |
          export BASE_URL=/main-preview
          yarn install --frozen-lockfile
          yarn build
      - name: Publish (PR)
        uses: rossjrw/pr-preview-action@v1
        if: github.event_name == 'pull_request'
        with:
          pages-base-url: docs.ereslibre.net
          source-dir: ./build/
          preview-branch: pr-previews
          clean-exclude: main-preview
          umbrella-dir: pr-preview
      - name: Publish (main)
        uses: rossjrw/pr-preview-action@v1
        if: github.event_name == 'push'
        with:
          pages-base-url: docs.ereslibre.net
          source-dir: ./build/
          preview-branch: pr-previews
          clean-exclude: pr-preview
          umbrella-dir: "${{ format('{0}-preview', github.ref_name) }}"
          action: deploy
          comment: "Deploy preview for ${{ format('{0}-preview', github.ref_name) }} branch"
