name: documentation
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '>= 18.0'
      - name: Build
        if: github.event_name != 'pull_request'
        run: |
          yarn install --frozen-lockfile
          yarn build
      - name: Build Preview
        if: github.event_name == 'pull_request'
        run: |
          export BASE_URL=pr-$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          yarn install --frozen-lockfile
          yarn build
      - name: Publish
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./build/
