name: documentation
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '>= 18.0'
      - name: Build Preview
        run: |
          export BASE_URL=/pr-preview/pr-$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          yarn install --frozen-lockfile
          yarn build
      - name: Publish
        if: github.event_name == 'pull_request'
        uses: rossjrw/pr-preview-action@v1
        with:
          pages-base-url: https://docs.ereslibre.net/pr-preview/
          source-dir: ./build/
          preview-branch: pr-previews
